# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estoque.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'estoque.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\restoque.proto\x12\x07\x65stoque\"\x1d\n\x0f\x43onsultaRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"s\n\x10GuitarraResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0e\n\x06modelo\x18\x03 \x01(\t\x12\r\n\x05preco\x18\x04 \x01(\x01\x12\x12\n\nquantidade\x18\x05 \x01(\x05\x12\x12\n\ndisponivel\x18\x06 \x01(\x08\"R\n\x0f\x43\x61\x64\x61stroRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0e\n\x06modelo\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\x01\x12\x12\n\nquantidade\x18\x04 \x01(\x05\"H\n\x10\x43\x61\x64\x61stroResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x11\n\tid_gerado\x18\x03 \x01(\x05\x32\xa4\x01\n\x0e\x45stoqueService\x12H\n\x11\x43onsultarGuitarra\x12\x18.estoque.ConsultaRequest\x1a\x19.estoque.GuitarraResponse\x12H\n\x11\x43\x61\x64\x61strarGuitarra\x12\x18.estoque.CadastroRequest\x1a\x19.estoque.CadastroResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estoque_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTAREQUEST']._serialized_start=26
  _globals['_CONSULTAREQUEST']._serialized_end=55
  _globals['_GUITARRARESPONSE']._serialized_start=57
  _globals['_GUITARRARESPONSE']._serialized_end=172
  _globals['_CADASTROREQUEST']._serialized_start=174
  _globals['_CADASTROREQUEST']._serialized_end=256
  _globals['_CADASTRORESPONSE']._serialized_start=258
  _globals['_CADASTRORESPONSE']._serialized_end=330
  _globals['_ESTOQUESERVICE']._serialized_start=333
  _globals['_ESTOQUESERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
